### ISSUE TITLE
Usar nombres expresivos donde se usan x, y xs etc

### ISSUE THREAD

**Issue by natoszme** [lublanco/Paradigmas#1]
Buenas! Para arrobarme usan @natoszme. Los issues los pueden usar como una lista de cosas para hacer y yo puedo ir agregándoles correcciones acá (en vez de usar sólo el mail)

**Comment by Nicbria** [comment]
ya fue modificado esto, al principio no sabíamos a que te habías referido con este punto en el mail jajaja
